
# Display name of workflow
name: Basic Workflow

#event
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        
        description: "Person to greet"
        default: "World"
        required: true
        type: string
      city:
        description: "Favorite city"
        required: true
        default: "China"
        type: choice
        options:
          - chennai
          - mumbai
          - coimbatore
      fav-color-blue:
        description: "Are you Member of Hepl"
        required: true
        type: boolean
#job
jobs:
  # single job
  greet:
    # Display name for the job
    name: "First Actions!"

    # The type of runner that the job will run on, in this case a Linus hosted runner
    runs-on:
      - ubuntu-latest

   #steps
    steps:
      # Runs command(s) using the runners shell and gets context from the github object
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}" 
          echo "Your favorite city is ${{ github.event.inputs.city }}"
          echo "Are you Member of Hepl: ${{ github.event.inputs.fav-color-blue }}"
